include("shared.lua")

if not ME.MapOK then return end

include("config/sfx.lua")
include("client/sfx.lua")
include("client/precache.lua")
include("client/rts_camera.lua")
include("client/board.lua")
include("client/hud_scale.lua")
include("client/hud_roster.lua")
include("client/hud_timer.lua")
include("client/hud_economy.lua")
include("client/hud_guide.lua")
include("client/hud_exit.lua")
include("client/hud_alliance.lua")
include("client/hud_chat.lua")
include("client/hud_minimap.lua")
include("client/hud_scoreboard.lua")
include("client/hud_endscreen.lua")
include("client/hud_custom.lua")
include("client/hud_build.lua")
include("client/build_place.lua")
include("client/hud_barge.lua")

include("config/menu.lua")
include("config/buildings.lua")
include("config/skins.lua")
include("menu/camera.lua")
include("menu/state.lua")
include("menu/animations.lua")
include("menu/styles.lua")
include("menu/scripts.lua")
include("menu/markup.lua")
include("menu/html.lua")
include("menu/overlays.lua")
include("menu/player_data.lua")
include("menu/block.lua")
include("menu/flow.lua")
include("client/menu_bridge.lua")

local HIDE = { CHudHealth = true, CHudBattery = true, CHudAmmo = true, CHudSecondaryAmmo = true, CHudCrosshair = true }
hook.Add("HUDShouldDraw", "ME_HideDefaultHUD", function(name)
	if HIDE[name] then return false end
end)
